config/routes.rb
Rails.application.routes.draw do
  
  get "static_pages/about"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "static_pages#home"

  #registration
  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  #basic login
  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  resources :users
  resources :products do
    resources :biddings
  end

  get '/products/:id/select_winner/:product_id', to: 'products#select_winner', as: 'select_winner' 
  put '/products/:id/stop_bidding', to: 'products#stop_bidding', as: 'stop_bidding_product'
  # get "/biddings/:id", to: "biddings#index", as:"biddings"
  # get 'biddings/new/:id', to: 'biddings#new', as: 'new_bidding'
  # get 'biddings/new/:id', to: 'biddings#new', as: 'custom_new_bidding'
  get 'my_biddings', to: 'biddings#my_biddings'
  get 'my_products', to: 'products#my_products'
end

app/views/shared/_flash.html.erb
</br>

<div class="container">
<% if flash[:notice]%>
<div class ="alert alert-info mt-4">
    <%= flash[:notice] %>
</div>
<% end %>

<% if flash[:alert]%>
<div class ="alert alert-warning mt-4">
    <%= flash[:alert] %>
</div>
<% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#", style="margin-left: 60px;">AUCTIONITY</a>
<div style="margin-right: 30px;">
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
</div>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ms-auto", style="margin-right: 60px;">
      <li class="nav-item active" style="margin-left: 30px;">
      <% if Current.user %>
      <%= link_to 'Home', products_path, class: 'nav-link' %>
<% end %>
      <% if !Current.user %>
      <li class="nav-item" style="margin-left: 30px;">
        <a class="nav-link" href="sign_in">Sign In</a>
      </li>
      <% end %>
      <% if Current.user %>
      <li class="dropdown" style="margin-left: 30px;">
      <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%=Current.user.username%>
      </a>
      
      <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
      <% if Current.user.role == 'auctioneer' %>
        <li><a class="dropdown-item" href="<%= my_products_path %>">My Products</a></li>
      <% else %>
        <li><a class="dropdown-item" href="<%= my_biddings_path %>">My Biddings</a></li>
      <% end %>
        <li><%= link_to "Logout", logout_path, method: :delete, class: "dropdown-item" %></li>
      </ul>
    </li>
    <% end %>
</nav>
