config/routes.rb
Rails.application.routes.draw do
  
  get "static_pages/about"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "static_pages#home"

  #registration
  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  #basic login
  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  resources :users
  resources :products do
    resources :biddings
  end

  get '/products/:id/select_winner/:product_id', to: 'products#select_winner', as: 'select_winner' 
  put '/products/:id/stop_bidding', to: 'products#stop_bidding', as: 'stop_bidding_product'
  # get "/biddings/:id", to: "biddings#index", as:"biddings"
  # get 'biddings/new/:id', to: 'biddings#new', as: 'new_bidding'
  # get 'biddings/new/:id', to: 'biddings#new', as: 'custom_new_bidding'
  get 'my_biddings', to: 'biddings#my_biddings'
  get 'my_products', to: 'products#my_products'
end

app/models/bidding.rb
class Bidding < ApplicationRecord

    belongs_to :user
    belongs_to :product
    validates :bid_amount,
    presence: true

    before_create :update_current_lowest_bid

# FOR CHECKING IF BID_AMOUNT >= CURRENT_LOWEST_BID + LOWEST_ALLOWABLE_BID


validate :minimum_bid_amount

  def minimum_bid_amount
    unless bid_amount && product.current_lowest_bid && product.lowest_allowable_bid
      # errors.add(:bid_amount, "can't be blank")
      return
    end

    min_bid = product.current_lowest_bid + product.lowest_allowable_bid
    if bid_amount < min_bid
      errors.add(:bid_amount, "must be greater than or equal to ₱ #{min_bid}")
    end
  end







    private

  def update_current_lowest_bid
    puts "update_current_lowest_bid method called"
    if bid_amount >= product.current_lowest_bid + product.lowest_allowable_bid
      product.update(current_lowest_bid: bid_amount)
      product.reload.current_lowest_bid
    end
  end
end

app/controllers/biddings_controller.rb
class BiddingsController < ApplicationController
    before_action :require_user_logged_in!
    before_action :check_role, only: [:new, :my_biddings]

        def index
            @product = Product.find(params[:product_id])            # @biddings = @product.biddings
            # if session[:user_id]
            #     @user = User.find(session[:user_id])
            # end
        end


        def new
            @product = Product.find(params[:product_id])
            @bidding = Bidding.new
        end

        def create
            puts "create action called"
            @product = Product.find(params[:product_id])
            @bidding = Bidding.new(bidding_params)
            
            # THIS IS FOR PRODUCT SHOW
            @bidding.product = @product # set the product for the bidding
            
            if @bidding.save
              @product.update_current_lowest_bid(@bidding.bid_amount)
            #   redirect_to products_path, notice: 'Bid was successfully placed.'
            # else
            #   render :new, status: 422
            # end
            
            # redirect to the appropriate page based on where the bid was placed
            if request.referrer == product_url(@product)
                redirect_to @product, notice: 'Bid was successfully placed.'
            else
                redirect_to products_path, notice: 'Bid was successfully placed.'
            end
            else
            render :new, status: 422
            end
          end



    
    def show 
    end
    
    # def edit 
    #     if @product.user != Current.user
    #         redirect_to products_path, notice: 'unauthorized access!'
    #      end
    # end
    def edit 
        @product = Product.find(params[:id])
        if @product && @product.user != Current.user
          redirect_to products_path, notice: 'unauthorized access!'
        end
    end
    
    def update
        @product = Product.find(params[:id])
        if @product.update(product_params)
            redirect_to products_path, notice: 'Product has been updated successfully.'
        else
            render :edit, status: 422
        end
    end
    
    def destroy
        if @product.user != Current.user
            redirect_to products_path, notice: 'unauthorized access!'
        else @product.destroy
            redirect_to products_path, notice: 'Product has been deleted successfully.'
        end
    end
    
    def stop_bidding
        @product = Product.find(params[:id])
        @product.update(bidding_allowed: false)
        redirect_to products_path, notice: "Bidding has been stopped for this product."
    end

    def my_biddings
        @biddings = Current.user.biddings.includes(:product).order(created_at: :desc)
    end

    private
    
        def product_params
            params.require(:product).permit(:name, :description, :lowest_allowable_bid, :starting_bid_price, :current_lowest_bid, :bidding_expiration, :image, :user_id, :bidding_allowed)
        end
    
        def bidding_params
            params.require(:bidding).permit(:user_id, :product_id, :bid_amount)
        end
          
        # def bidding_params
        #     params.require(:bidding).permit(:bid_amount).merge(product_id: params[:product_id], user_id: current_user.id)
        #   end

        # def set_micropost
        #     @product = Product.find(params[:id])
        # end
   
        def check_role
            unless Current.user&.bidder?
              redirect_to products_path, alert: "You are not authorized to access this page."
            end
          end
    
end

app/helpers/biddings_helper.rb
module BiddingsHelper
end

app/views/biddings/index.html.erb

<div class="container">
<h1>This is <%=@product.name%> bidding page.</h1>
<!----<% if Current.user.role == 'bidder' %>--->


<%= link_to 'Made a Bid',new_bidding_path, {:class => 'btn btn-outline-success m-3'}%>

<p><strong>ITEM: </strong><%=@product.name%></p>
        <p class="card-text"><strong>DESCRIPTION:</strong>
        <%=@product.description %>
        </p>
        <% if (Time.zone.now - @product.created_at) > 3.day %>
          <h7 class="card-title"><%=@product.created_at.strftime("%B %d %Y")%></h7>
        <% else %>
          <h7 class="card-title"><%=time_ago_in_words(@product.created_at)%> ago</h7>
        <% end %>
      </br></br>
      <p><strong>Lowest Allowable Bid: </strong><%= @product.lowest_allowable_bid %></p>
      <p><strong>Starting Bid Price: </strong><%= @product.starting_bid_price%></p>
      <p><strong>Current Lowest Bid: </strong><%= @product.current_lowest_bid%></p>
      <p><strong>Bidding Expiration: </strong><%= @product.bidding_expiration.strftime("%B %d, %Y at %I:%M %p") %></p>


<% end %>
  
</div>
</br>
</br>


app/views/biddings/my_biddings.html.erb
<div style="margin-left: 50px;"><h1>MY BIDDINGS</h1></div>








<div class="container">
<table class="table table-hover">
  <thead>
    <tr>
      <th>Product Image</th>
      <th>Product Name</th>
      <th>Bid Placed</th>
      <th>Bid Date</th>
      <th>Bidding Status</th>
      <th>Expiration Date</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @biddings.each do |bidding| %>
      <tr>
        <td><%= cl_image_tag(bidding.product.image_url, width: 150) %></td>
        <td><%= bidding.product.name %></td>
        <td>₱<%= bidding.bid_amount %></td>
        <td><%= bidding.created_at.strftime('%m/%d/%Y at %I:%M %p') %></td>
        <td>
            <% if bidding.product.bidding_allowed == true %>
                Ongoing
            <% else %>
                Ended
            <% end %>
        
        </td>
        <td><%= bidding.product.bidding_expiration.strftime('%m/%d/%Y at %I:%M %p') %></td>
        <td><%= link_to "View Product", bidding.product, class: "btn btn-outline-secondary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/biddings/new.html.erb
<section class="vh-100">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-xl-11">
        <div class="card" style="border-radius: 1rem;">
         
            <div class="row g-0">
                <div class="col-md-6 col-lg-5 d-none d-md-block">
                <!--FOR NEW BID VIEW--->
                    <% if controller_name == 'biddings' && action_name == 'new' %>
                    <%= image_tag("bid.png", class: "img-fluid", style: "border-radius: 1rem 0 0 1rem;") %>
                    <% end %>

                <!--FOR EDIT VIEW--->
                    <% if controller_name == 'biddings' && action_name == 'edit' %>
                    <%#= image_tag("bid.png", class: "img-fluid", style: "border-radius: 1rem 0 0 1rem;") %>
                    <% end %>      

                <!--FOR VIEW WITH ERRORS--->
                    <% if @bidding.errors.any? %>
                    <%= cl_image_tag(@product.image_url, class: "img-fluid", style: "border-radius: 1rem 0 0 1rem;") %>
                    <% end %> 
                </div>

                <div class="col-md-6 col-lg-7 d-flex align-items-center">
                    <div class="card-body p-4 p-lg-5">
                        <div class="d-flex align-items-center mb-3 pb-1">
                            <!--FOR NEW VIEW--->
                            <% if controller_name == 'biddings' && action_name == 'new' %>
                                <span class="h1 fw-bold mb-0">Add Item</span>
                            <% end %>

                            <!--FOR EDIT VIEW--->
                            <% if controller_name == 'biddings' && action_name == 'edit' %>
                                <span class="h1 fw-bold mb-0">Edit Item</span>
                            <% end %>

                            <!--FOR EDIT VIEW--->
                            <% if @bidding.errors.any? %>
                                <span class="h1 fw-bold mb-0">Try Again</span>
                            <% end %>
                        </div>


    <strong>YOU ARE BIDDING FOR ITEM:  <%= @product.name %></strong><br>
    <% if @product.biddings.any? %>
      <% bidding = @product.biddings.order(created_at: :desc).first %>
      <i class="fas fa-crown"></i><strong>Current Highest Bid:</strong> ₱<%= @product.current_lowest_bid %>
    <% else %>
      <strong>No bids yet</strong>
    <% end %>
</br>

  <i class="fa fa-arrow-down"></i><strong>Minimum Bid:</strong> ₱<%= @product.lowest_allowable_bid %>

<%= form_with(model: [@product, @bidding], local: true, data: { turbo: true }) do |form| %>
                            <% if @bidding.errors.any? %>
                                <div class="alert alert-danger">
                                    <% @bidding.errors.full_messages.each do |msg| %>
                                        <div><%= msg %></div>
                                    <% end %>
                                </div>
                            <% end %>


                        <!--[PRODUCT ID]--->
                        <%= form.hidden_field :product_id, value: @product.id %>
                        <!--[USER ID]--->
                            <%= form.hidden_field :user_id, value: Current.user.id %>
                        <!--[BID AMOUNT]--->
                            <div class="form-outline mb-4">
                                <%= form.label :bid_amount %><br>
                                <%= form.number_field :bid_amount, class: "form-control" %>
                            </div>

                            <div class="mb-3">
                                <%= form.submit "Place bid", ({:class => 'btn btn-success'})%>
                            </div>
                        <% end %>


                    </div>
                </div>
            </div>
        </div>
    </div>
      </br>
      </br>
</div>
    
</section>




app/views/biddings/show.html.erb
<%=@bidding.user_id%>
<%=@bidding.amount%>
<%=@bidding.user.username%>
<%=@bidding.product.id%>