config/routes.rb
Rails.application.routes.draw do
  
  get "static_pages/about"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "static_pages#home"

  #registration
  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  #basic login
  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  resources :users
  resources :products do
    resources :biddings
  end

  get '/products/:id/select_winner/:product_id', to: 'products#select_winner', as: 'select_winner' 
  put '/products/:id/stop_bidding', to: 'products#stop_bidding', as: 'stop_bidding_product'
  # get "/biddings/:id", to: "biddings#index", as:"biddings"
  # get 'biddings/new/:id', to: 'biddings#new', as: 'new_bidding'
  # get 'biddings/new/:id', to: 'biddings#new', as: 'custom_new_bidding'
  get 'my_biddings', to: 'biddings#my_biddings'
  get 'my_products', to: 'products#my_products'
end

app/models/product.rb
class Product < ApplicationRecord
    before_save :check_bidding_expiration
    # before_save :set_current_lowest_bid
    after_create :set_initial_current_lowest_bid

    
  def set_initial_current_lowest_bid
    self.current_lowest_bid = self.starting_bid_price
    self.save
  end

    belongs_to :user
    has_many :biddings, dependent: :destroy
    validates :name, :description, :lowest_allowable_bid, :starting_bid_price, :bidding_expiration, 
    presence: true


    validate :validate_bidding_allowed

    def validate_bidding_allowed
      if bidding_allowed && bidding_expiration && bidding_expiration <= Time.current
        errors.add(:bidding_allowed,"cannot be set. Bidding Expiration must be ahead of the Current Time.")
      end
    end


    def update_current_lowest_bid(bid_amount)
        puts "updating"
        if current_lowest_bid.nil? || bid_amount > current_lowest_bid + lowest_allowable_bid
            puts "updating"
            self.current_lowest_bid = bid_amount
          save
        end
      end

      def winner
        if self.bidding_allowed
          # return nil if bidding is still allowed
          return nil
        else
          # find the user who made the highest bid
          highest_bid = Bidding.where(product_id: self.id).maximum(:bid_amount)
          winner = Bidding.find_by(product_id: self.id, bid_amount: highest_bid)
          return winner
        end
      end










    private
    # CALLBACK METHOD FOR CHECKING BIDDING EXPIRATION
    def check_bidding_expiration
        if self.bidding_expiration < Time.current
          self.bidding_allowed = false
        end
    end

  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :require_user_logged_in!
    before_action :check_role, only: [:new, :my_products]
    def index
        # @products = Product.all.order(:created_at)
        # @product = Product.new
        @products = Product.includes(:biddings).all.order(:created_at)
        @updated_product = flash[:updated_product]
        @products.each do |product|
            if product.bidding_expiration < Time.current
              product.update(bidding_allowed: false)
            end
        end
    end

    def new
        @product = Product.new
    end

    def create
        begin
            result = Cloudinary::Uploader.upload(params[:product][:image], use_filename: true, unique_filename: false)
          rescue CloudinaryException => e
            flash[:alert] = "#{e.message}. Must be a JPG, JPEG, or PNG file"
            redirect_to new_product_path and return
          end
          
          @product = Product.new(product_params(result))
          @product.image_url = result['secure_url']
        if @product.save 
          redirect_to products_path, notice: 'Product has been created successfully.'
        else
          render :new, status: 422
        end
      end
      

    def show
        @product = Product.find(params[:id])
        @product = Product.includes(biddings: :user).find(params[:id])
    end


    def my_products
        @user = Current.user
        @products = @user.products.includes(:biddings)
    end


    def select_winner
        @product = Product.find(params[:id])
    
        if @product.update(bidding_allowed: false)
          redirect_to request.referer, notice: "Bidding Ended Successfully."
        else
          render :select_winner
        end
    end
    





def edit 
    @product = Product.find(params[:id])
    if @product && @product.user != Current.user
      redirect_to products_path, notice: 'unauthorized access!'
    end
end

def update
    @product = Product.find(params[:id])
    begin
        result = Cloudinary::Uploader.upload(params[:product][:image], use_filename: true, unique_filename: false)
      rescue CloudinaryException => e
        flash[:alert] = "#{e.message}. Must be a JPG, JPEG, or PNG file"
        redirect_to edit_product_path and return
      end
    if @product.update(product_params(result))
        redirect_to products_path, notice: 'Product has been updated successfully.'
    else
        render :edit, status: 422
    end
end

def destroy
    @product = Product.find(params[:id])
    if @product.user != Current.user
        redirect_to request.referer, notice: 'unauthorized access!'
    else
      @product.destroy
      redirect_to request.referer, notice: 'Product has been deleted successfully.'
    end
end

def stop_bidding
    @product = Product.find(params[:id])
    @product.update(bidding_allowed: false)
    redirect_to products_path, notice: "Bidding has been stopped for this product."
end



private

def product_params(result)
    params.require(:product).permit(:name, :description, :lowest_allowable_bid, :starting_bid_price, :bidding_expiration, :current_lowest_bid, :bidding_allowed, :user_id).merge(image_url: result['secure_url'])
  end

    # def set_micropost
    #     @product = Product.find(params[:id])
    # end

    def check_role
        unless Current.user&.auctioneer?
          redirect_to products_path, alert: "You are not authorized to access this page."
        end
      end


end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/index.html.erb
<div style="margin-left: 50px;"><h1>PRODUCTS</h1>
<% if Current.user.role == 'auctioneer' %>
<%= link_to 'Add Item',new_product_path, {:class => 'btn btn-outline-primary m-3'}%>
<% end %></div>
<div class="container">
<div class="row row-cols-1 row-cols-md-3 g-4">
<% @products.each do|product| %>
  <div class="col">

    <div class="card h-100">
    <div class="card-header">
    <div class="d-flex justify-content-between">
    <% if product.bidding_allowed %>
    <% if product.biddings.any? %>
      <div><i class="fas fa-crown"></i><strong>Current Bid: </strong> <% if product.biddings.any? %>
        <% bidding = product.biddings.order(created_at: :desc).first %>
        <%= bidding.user.username %>
        
      <% else %>
        <td>No bids yet</td>
      <% end %>
      </div>
      <% end %>
      <div class="d-flex align-items-center">
        <div class="ml-auto"><i class="fas fa-money-bill"></i>₱<%= product.current_lowest_bid %></div>
      </div>

      <% else %>
      <% if product.biddings.any? %>
      <div><i class="fas fa-crown"></i><strong>Winner: </strong> <% if product.biddings.any? %>
        <% bidding = product.biddings.order(created_at: :desc).first %>
        <%= bidding.user.username %>
      <% end %>
      </div>
  
      <div class="d-flex align-items-center">
        <div class="ml-auto"><i class="fas fa-money-bill"></i>₱<%= product.current_lowest_bid %></div>
      </div>

      <% else %>

      <div><strong>No winner </strong>
    </div>
      <% end %>
      <% end %>
    </div>
  </div>

    <%= cl_image_tag(product.image_url, height: 410) %>


    <div class="card-header">
    <div class="d-flex justify-content-between">
    <div>
    <a href="<%= product_path(product) %>" style="color: blue; text-decoration: none;"><div>
    <i class="fas fa-shopping-bag"></i><strong>Product: </strong>
    <%= product.name %>
  </div></a>
  
  </div>
      <% if product.bidding_allowed %>
       <div class="d-flex align-items-center">
       <i class="fas fa-stopwatch"></i>
        <div class="timer" data-expiration-time="<%= product.bidding_expiration %>"></div>
      </div>
      <% if product.user == Current.user %>
        <% if Current.user.role == 'auctioneer' %>
        <%= button_to "Stop Bidding", stop_bidding_product_path(product), method: :put, class: "btn btn-danger stop-bidding-button", id: "stop-bidding-button" %>
        <% end %>
        <% end %>
        <% else %>
        <div class="d-flex align-items-center">
          <i class="fas fa-stopwatch"></i>
          <span class="ml-2">Ended</span>
        </div>
      <% end %>
    </div>
  </div>






  <ul class="list-group list-group-flush">

    <li class="list-group-item d-flex justify-content-between align-items-center">
    <div>
      <i class="fas fa-user"></i><strong>Posted by: </strong>
      <span><%= product.user.username %></span>
    </div>
    <div>
    <i class="fas fa-gavel"></i><strong>Starting bid:</strong>
    ₱<%= product.starting_bid_price%>
    </div>
  </li>


  <li class="list-group-item d-flex justify-content-between align-items-center">
    <div>
  <i class="fas fa-hourglass-end"></i></i></i>
  <%= product.bidding_expiration.strftime("%-m/%-d/%Y at %I:%M %p") %>
  </div>
  <div>
  <i class="fa fa-arrow-down"></i><strong>Minimum bid: </strong>
  ₱<%=product.lowest_allowable_bid%>
  </div>
</li>


  <li class="list-group-item"><p class="card-text">
  <i class="fas fa-align-left"></i><strong>Description: </strong>
  <%=product.description %>
  </li>


  <% if Current.user.role == 'bidder' %>

  <% if product.bidding_allowed %>
  
  <li class="list-group-item">
  <div class="d-flex justify-content-between">
  
  <button class="btn btn-link btn-light text-decoration-none text-success" data-bs-toggle="collapse" data-bs-target="#place-bid-section-<%= product.id %>" aria-expanded="true" aria-controls="place-bid-section-<%= product.id %>">
  <h7><i class="fas fa-gavel"></i><strong>Place Bid </strong><i class="fa fa-angle-down"></i></h7>
</button>
  </div>
  <div id="place-bid-section-<%= product.id %>" class="collapse">
    <ul class="list-group">
      <li class="list-group-item">
        <div class="d-flex justify-content-between">
          <div>
            <% if product.biddings.any? %>
              <% bidding = product.biddings.order(created_at: :desc).first %>
              <i class="fas fa-crown"></i><strong>Current Highest Bid:</strong> ₱<%= product.current_lowest_bid %>
            <% else %>
              <strong>No bids yet</strong>
            <% end %>
          </div>
        </div>
      </li>
      <li class="list-group-item">
        <div class="d-flex justify-content-between">
          <div>
          <i class="fa fa-arrow-down"></i><strong>Minimum Bid:</strong> ₱<%= product.lowest_allowable_bid %>
          </div>
        </div>
      </li>
      <!-- Add form to place a bid here -->
      <li class="list-group-item text-center">
</br>
      <%= form_with(model: [product, Bidding.new], local: true, data: { turbo: true }) do |form| %>
        <% if form.object.errors.any? %>
          <div class="alert alert-danger">
            <% form.object.errors.full_messages.each do |msg| %>
              <div><%= msg %></div>
            <% end %>
          </div>
        <% end %>
        <div class="row">
          <div class="col-md-8 mb-3">
            <%= form.hidden_field :product_id, value: product.id %>
            <%= form.hidden_field :user_id, value: Current.user.id %>
            <div class="form-group">
              <%= form.number_field :bid_amount, class: "form-control", placeholder: "Bid Must Be >= ₱ #{product.current_lowest_bid + product.lowest_allowable_bid}" %>
              
            </div>
          </div>
          <div class="col-md-4 mb-3">
            <div class="form-group">
              <%= form.submit "Place Bid", class: "btn btn-success btn-block" %>
            </div>
          </div>
        </div>
      <% end %>
      </li>
    </ul>
  </div>
</li>


<% end %>

<% end %>








  







  

<!-----


<li class="list-group-item text-center">
</br>
      <%= form_with(model: [product, Bidding.new], local: true, data: { turbo: true }) do |form| %>
        <% if form.object.errors.any? %>
          <div class="alert alert-danger">
            <% form.object.errors.full_messages.each do |msg| %>
              <div><%= msg %></div>
            <% end %>
          </div>
        <% end %>
        <div class="row">
          <div class="col-md-8 mb-3">
            <%= form.hidden_field :product_id, value: product.id %>
            <%= form.hidden_field :user_id, value: Current.user.id %>
            <div class="form-group">
              <%= form.number_field :bid_amount, class: "form-control", placeholder: "Bid Must Be => #{product.current_lowest_bid + product.lowest_allowable_bid}" %>
              
            </div>
          </div>
          <div class="col-md-4 mb-3">
            <div class="form-group">
              <%= form.submit "Place Bid", class: "btn btn-primary btn-block" %>
            </div>
          </div>
        </div>
      <% end %>
      </li>



      ------>
</ul>




<!--
<% if (Time.zone.now - product.created_at) > 3.day %>
  <h7 class="card-title"><%=product.created_at.strftime("%B %d %Y")%></h7>
<% else %>
  <h7 class="card-title"><%=time_ago_in_words(product.created_at)%> ago</h7>
<% end %>
-->





<!-----
      <div class="card-body">
  


      <%= product.bidding_allowed %>
      
      </div>
      <li style = "list-style-type: none; padding-left: 20px">
      <div class="product-card" data-product-id="<%= product.id %>" data-bidding-expiration="<%= product.bidding_expiration %>">
    
    
        <% if product.bidding_allowed %>
            <div class="timer" data-expiration-time="<%= product.bidding_expiration %>"></div>  
        <%= button_to "Stop Bidding", stop_bidding_product_path(product), method: :put, class: "btn btn-danger stop-bidding-button", id: "stop-bidding-button" %>
            <% else %>
          <p>Expired</p>
        <% end %>
 
        </div>  

    <input type="hidden" class="expiration-time" value="<%= product.bidding_expiration %>">

      
            <%= link_to 'View', product, {:class => 'btn btn-light'} %>
            <% if product.user == Current.user %>
            <%= link_to 'Edit', edit_product_path(product), {:class => 'btn btn-light'} %>
            <%= link_to "Delete", product, :class => 'btn btn-light', data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
                     
            <% end %>
            </li>
        </br>

        ---->
    </div>

   

  </div>
  <% end %>
  
</div>
</div>
</br>
</br>

<%= javascript_include_tag ("timer.js")%>



app/views/products/my_products.html.erb

<div class = "container">
<h1>YOUR PRODUCTS (<%= @user.username %>)</h1>


<div class="container">
<table class="table table-hover">
  <thead>
    <tr>
      <th>Product Image</th>
      <th>Product Name</th>
      <th>Product Description</th>
      <th>Starting Bid</th>
      <th>Lowest Allowable Bid</th>
      <th>Current Lowest Bid</th>
      <th>Bidder Name</th>
      <th>Bidding Status</th>
      <th>Expiration Date</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @products.each do |product| %>
      <tr>
        <td> <%= cl_image_tag(product.image_url, width: 150) %></td>
        <td><a href="<%= product_path(product) %>" style="color: blue; text-decoration: none;"><%= product.name %></a></td>













        <td><%= product.description %></td>
        <td>₱<%= product.starting_bid_price %></td>
        <td>₱<%= product.lowest_allowable_bid %></td>
        <td>
        <% if product.current_lowest_bid == product.starting_bid_price %>
        No Bids Yet
        <% else %>
        ₱<%= product.current_lowest_bid %>
        <% end %>
        </td>
        <td>
        
        <% if product.biddings.any? %>
        <% bidding = product.biddings.order(created_at: :desc).first %>
        <%= bidding.user.username %>
      <% else %>
        No Bidder Yet
      <% end %>
        
   
        </td>
        <td>
            <% if product.bidding_allowed == true %>
                Ongoing
            <% else %>
                Ended
            <% end %>
        
        </td>
        <td><%= product.bidding_expiration.strftime('%m/%d/%Y at %I:%M %p') %></td>
        
        <td><li class="list-group-item">
        <div class="d-flex justify-content-between">
        
        <button class="btn btn-link btn-light text-decoration-none text-warning" data-bs-toggle="collapse" data-bs-target="#bid-logs-section-<%= product.id %>" aria-expanded="true" aria-controls="place-bid-section-<%= product.id %>">
        <h7><i class="fa fa-history"></i><strong>Bidding Log </strong><i class="fa fa-angle-down"></i></h7>
        </button>
        </div>
        
        <div id="bid-logs-section-<%= product.id %>" class="collapse">
          <ul class="list-group">
            <table>
            <thead>
              <tr>
                <th>Bidder Username</th>
                <th>Bid Amount</th>
                <th>Bid Date</th>
              </tr>
            </thead>
            <tbody>
              <% product.biddings.each do |bidding| %>
                <tr>
                  <td><%= bidding.user.username %></td>
                  <td>₱<%= bidding.bid_amount %></td>
                  <td><%= bidding.created_at.strftime("%-m/%-d/%Y %I:%M %p") %></td>
                </tr>
              <% end %>
            </tbody>
          </table>

            </div>
</td>        
<td>
<% if product.bidding_allowed %>
  <% if Current.user.role == 'auctioneer' %>
  <%= button_to "Stop Bidding", select_winner_path(id: product.id, product_id: product.id), method: :get, class: "btn btn-danger stop-bidding-button", id: "stop-bidding-button" %>
  <% end %>
<% else %>
<% if product.bidding_allowed %>
<div class="alert alert-warning">
  Bidding is still open.
</div>
<% elsif product.winner.nil? %>
<div class="alert alert-warning">
  No Winner.
</div>
<% else %>
<div class="alert alert-info"><% if product.present? && !product.bidding_allowed %>
<% if Current.user.role == 'auctioneer' %>
  <% if product.winner %>
    <p>Winner: <%= product.winner.user.username %></p>
  <% else %>

  <% end %>
<% end %>
<% end %>
</div>
<% end %>

<% end %>
</td>
<td>
<%= link_to 'Edit', edit_product_path(product), {:class => 'btn btn-light'} %>
</td>
<td>
<%= link_to "Delete", product, :class => 'btn btn-warning', data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
</td>
        </tr>
    <% end %>
  </tbody>
</table>
</div>


























app/views/products/new.html.erb
<div style="margin-left: 50px;"><%= link_to 'Back',products_path, {:class => 'btn btn-outline-primary'} %></div>
<%= render "form", product: @product %>

app/views/products/show.html.erb
<div class="container">

<div class="container">
<div class="row">
    <div class="col">

    <% if Current.user.role == 'bidder' %>

    <% if @product.bidding_allowed %>
  
    <li class="list-group-item">
    <div class="d-flex justify-content-between">
    
    <button class="btn btn-link btn-light text-decoration-none text-success" data-bs-toggle="collapse" data-bs-target="#place-bid-section-<%= @product.id %>" aria-expanded="true" aria-controls="place-bid-section-<%= @product.id %>">
    <h7><i class="fas fa-gavel"></i><strong>Place Bid </strong><i class="fa fa-angle-down"></i></h7>
  </button>
    </div>
    <div id="place-bid-section-<%= @product.id %>" class="collapse">
      <ul class="list-group">
        <li class="list-group-item">
          <div class="d-flex justify-content-between">
            <div>
              <% if @product.biddings.any? %>
                <% bidding = @product.biddings.order(created_at: :desc).first %>
                <i class="fas fa-crown"></i><strong>Current Highest Bid:</strong>₱<%= @product.current_lowest_bid %>
              <% else %>
                <strong>No bids yet</strong>
              <% end %>
            </div>
          </div>
        </li>
        <li class="list-group-item">
          <div class="d-flex justify-content-between">
            <div>
            <i class="fa fa-arrow-down"></i><strong>Minimum Bid:</strong> ₱<%= @product.lowest_allowable_bid %>
            </div>
          </div>
        </li>
  
        <li class="list-group-item text-center">
  </br>
        <%= form_with(model: [@product, Bidding.new], local: true, data: { turbo: true }) do |form| %>
          <% if form.object.errors.any? %>
            <div class="alert alert-danger">
              <% form.object.errors.full_messages.each do |msg| %>
                <div><%= msg %></div>
              <% end %>
            </div>
          <% end %>
          <div class="row">
            <div class="col-md-8 mb-3">
              <%= form.hidden_field :@product_id, value: @product.id %>
              <%= form.hidden_field :user_id, value: Current.user.id %>
              <div class="form-group">
                <%= form.number_field :bid_amount, class: "form-control", placeholder: "Bid Must Be >= ₱ #{@product.current_lowest_bid + @product.lowest_allowable_bid}" %>
                
              </div>
            </div>
            <div class="col-md-4 mb-3">
              <div class="form-group">
                <%= form.submit "Place Bid", class: "btn btn-success btn-block" %>
              </div>
            </div>
          </div>
        <% end %>
        </li>
      </ul>
    </div>
  </li>
  
  
  <% end %>
  <% end %>





    <div class="card h-100">
    <div class="card-header">
    <div class="d-flex justify-content-between">
    <% if @product.bidding_allowed %>
    <% if @product.biddings.any? %>
      <div><i class="fas fa-crown"></i><strong>Current Bid: </strong> <% if @product.biddings.any? %>
        <% bidding = @product.biddings.order(created_at: :desc).first %>
        <%= bidding.user.username %>
      <% else %>
        <td>No bids yet</td>
      <% end %>
      </div>
      <% end %>
      <div class="d-flex align-items-center">
        <div class="ml-auto"><i class="fas fa-money-bill"></i>₱<%= @product.current_lowest_bid %></div>
      </div>
  
      <% else %>
      <% if @product.biddings.any? %>
      <div><i class="fas fa-crown"></i><strong>Winner: </strong> <% if @product.biddings.any? %>
        <% bidding = @product.biddings.order(created_at: :desc).first %>
        <%= bidding.user.username %>
      <% end %>
      </div>
  
      <div class="d-flex align-items-center">
        <div class="ml-auto"><i class="fas fa-money-bill"></i>₱<%= @product.current_lowest_bid %></div>
      </div>

      <% else %>

      <div><strong>No winner </strong>
    </div>
      <% end %>
      <% end %>
    </div>
  </div>

    <%= cl_image_tag(@product.image_url, height: 410) %>


    <div class="card-header">
    <div class="d-flex justify-content-between">
      <div>
      <i class="fas fa-shopping-bag"></i><strong>Product: </strong>
      <%=@product.name%>
      </div>
      <% if @product.bidding_allowed %>
       <div class="d-flex align-items-center">
       <i class="fas fa-stopwatch"></i>
        <div class="timer" data-expiration-time="<%= @product.bidding_expiration %>"></div>
      </div>
        <% if Current.user.role == 'auctioneer' %>
        <% if @product.user == Current.user %>
        <%= button_to "Stop Bidding", stop_bidding_product_path(@product), method: :put, class: "btn btn-danger stop-bidding-button", id: "stop-bidding-button" %>
        <% end %><% end %>
        <% else %>
        <div class="d-flex align-items-center">
          <i class="fas fa-stopwatch"></i>
          <span class="ml-2">Ended</span>
        </div>
      <% end %>
    </div>
  </div>






  <ul class="list-group list-group-flush">

    <li class="list-group-item d-flex justify-content-between align-items-center">
    <div>
      <i class="fas fa-user"></i><strong>Posted by: </strong>
      <span><%= @product.user.username %></span>
    </div>
    <div>
    <i class="fas fa-gavel"></i><strong>Starting bid:</strong>
    ₱<%= @product.starting_bid_price%>
    </div>
  </li>


  <li class="list-group-item d-flex justify-content-between align-items-center">
    <div>
  <i class="fas fa-hourglass-end"></i></i></i>
  <%= @product.bidding_expiration.strftime("%-m/%-d/%Y at %I:%M %p") %>
  </div>
  <div>
  <i class="fa fa-arrow-down"></i><strong>Minimum bid: </strong>
  ₱<%= @product.lowest_allowable_bid%>
  </div>
</li>


  <li class="list-group-item"><p class="card-text">
  <i class="fas fa-align-left"></i><strong>Description: </strong>
  <%= @product.description %>
  </li>



</div>  

      </div>
<div class="col">
<li class="list-group-item">
<div class="d-flex justify-content-between">

<button class="btn btn-link btn-light text-decoration-none text-warning" data-bs-toggle="collapse" data-bs-target="#bid-logs-section-<%= @product.id %>" aria-expanded="true" aria-controls="place-bid-section-<%= @product.id %>">
<h7><i class="fa fa-history"></i><strong>Bidding Log </strong><i class="fa fa-angle-down"></i></h7>
</button>
</div>

<div id="bid-logs-section-<%= @product.id %>" class="collapse">
  <ul class="list-group">
    <table>
    <thead>
      <tr>
        <th>Bidder Username</th>
        <th>Bid Amount</th>
        <th>Bid Date</th>
      </tr>
    </thead>
    <tbody>
      <% @product.biddings.each do |bidding| %>
        <tr>
          <td><%= bidding.user.username %></td>
          <td>₱<%= bidding.bid_amount %></td>
          <td><%= bidding.created_at.strftime("%-m/%-d/%Y at %I:%M %p") %></td>
        </tr>
      <% end %>
    </tbody>
  </table>





    </div>
    
    </div>


    
      </div>


</br>

<%= javascript_include_tag ("timer.js")%>



  







  
